"""Updated user table

Revision ID: 1984e73a6327
Revises: e9a8bc3fa182
Create Date: 2026-09-23 14:47:14.099750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1984e73a6327'
down_revision: Union[str, Sequence[str], None] = 'e9a8bc3fa182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=False))
    op.drop_column('users', 'refresh_token_expiry')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('refresh_token_expiry', mysql.DATETIME(), nullable=False))
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
