"""Added feature flag environment table

Revision ID: 22859ab4df98
Revises: 4723b26dbedf
Create Date: 2026-09-23 18:04:51.790386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22859ab4df98'
down_revision: Union[str, Sequence[str], None] = '4723b26dbedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flag_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_flag_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_flag_id', 'environment_id', name='uq_feature_flag_environment')
    )
    op.create_index(op.f('ix_feature_flag_environments_id'), 'feature_flag_environments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flag_environments_id'), table_name='feature_flag_environments')
    op.drop_table('feature_flag_environments')
    # ### end Alembic commands ###
