"""Updated user table

Revision ID: 7e5e6768809c
Revises: a88f4cd4ab67
Create Date: 2026-09-23 15:39:07.940715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e5e6768809c'
down_revision: Union[str, Sequence[str], None] = 'a88f4cd4ab67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'reset_token_expiry',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token_expiry',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'reset_token',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
