"""Added feature rollout table

Revision ID: 7ebfc7915a68
Revises: 22859ab4df98
Create Date: 2026-09-25 14:45:03.687840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebfc7915a68'
down_revision: Union[str, Sequence[str], None] = '22859ab4df98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_rollouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_flag_environment_id', sa.Integer(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_flag_environment_id'], ['feature_flag_environments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_rollouts_id'), 'feature_rollouts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_rollouts_id'), table_name='feature_rollouts')
    op.drop_table('feature_rollouts')
    # ### end Alembic commands ###
