"""Updated role table

Revision ID: a88f4cd4ab67
Revises: 1984e73a6327
Create Date: 2026-09-23 15:24:37.249000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a88f4cd4ab67'
down_revision: Union[str, Sequence[str], None] = '1984e73a6327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'new_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('new_column', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
